# swagger.yaml
openapi: 3.0.0
info:
  title: Sample API
  description: API documentation for a sample application.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /products:
    get:
      summary: Retrieve a list of products
      tags:
        - Products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        prod_name:
          type: string
        prod_desc:
          type: string
        prod_price:
          type: number
        update_at:
          type: string
          format: date-time
